/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_caoyue_bihu_data_network_ApiKeys */

#ifndef _Included_cn_com_caoyue_bihu_data_network_ApiKeys
#define _Included_cn_com_caoyue_bihu_data_network_ApiKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_caoyue_bihu_data_network_ApiKeys
 * Method:    getHaruueKnowWebApikey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_com_caoyue_bihu_data_network_ApiKeys_getHaruueKnowWebApikey
  (JNIEnv *, jclass);

/*
 * Class:     cn_com_caoyue_bihu_data_network_ApiKeys
 * Method:    getHaruueStorageServer2Apikey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_com_caoyue_bihu_data_network_ApiKeys_getHaruueStorageServer2Apikey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
